// GENERATED by scripts/gen-theme-index.mjs. Do not edit.
import type { Theme } from "../types";
import t_amber_crt from "./amber-crt";
import t_aurora from "./aurora";
import t_ayu_mirage from "./ayu-mirage";
import t_bento_playful from "./bento-playful";
import t_blueprint from "./blueprint";
import t_catppuccin_latte from "./catppuccin-latte";
import t_catppuccin_mocha from "./catppuccin-mocha";
import t_coffee from "./coffee";
import t_colorblind_safe from "./colorblind-safe";
import t_cyberpunk_neon from "./cyberpunk-neon";
import t_dark from "./dark";
import t_desert from "./desert";
import t_docker_whale from "./docker-whale";
import t_dracula from "./dracula";
import t_editorial from "./editorial";
import t_everforest from "./everforest";
import t_flat_minimal from "./flat-minimal";
import t_fluent from "./fluent";
import t_forest from "./forest";
import t_github_dark from "./github-dark";
import t_github_light from "./github-light";
import t_graphite from "./graphite";
import t_gruvbox_dark from "./gruvbox-dark";
import t_gruvbox_light from "./gruvbox-light";
import t_high_contrast from "./high-contrast";
import t_kanagawa from "./kanagawa";
import t_lavender from "./lavender";
import t_light from "./light";
import t_material_you from "./material-you";
import t_midnight from "./midnight";
import t_mint from "./mint";
import t_monokai from "./monokai";
import t_neo_brutalism from "./neo-brutalism";
import t_neumorphism from "./neumorphism";
import t_night_owl from "./night-owl";
import t_nord from "./nord";
import t_nord_light from "./nord-light";
import t_ocean from "./ocean";
import t_oled_black from "./oled-black";
import t_one_dark from "./one-dark";
import t_paper from "./paper";
import t_retro_95 from "./retro-95";
import t_rose from "./rose";
import t_rose_pine from "./rose-pine";
import t_rose_pine_dawn from "./rose-pine-dawn";
import t_sand from "./sand";
import t_sepia from "./sepia";
import t_snow from "./snow";
import t_solarized_dark from "./solarized-dark";
import t_solarized_light from "./solarized-light";
import t_sunset from "./sunset";
import t_terminal from "./terminal";
import t_tokyo_night from "./tokyo-night";
import t_ubuntu_aubergine from "./ubuntu-aubergine";

export const themeModules: Array<Theme | Theme[]> = [
  t_amber_crt,
  t_aurora,
  t_ayu_mirage,
  t_bento_playful,
  t_blueprint,
  t_catppuccin_latte,
  t_catppuccin_mocha,
  t_coffee,
  t_colorblind_safe,
  t_cyberpunk_neon,
  t_dark,
  t_desert,
  t_docker_whale,
  t_dracula,
  t_editorial,
  t_everforest,
  t_flat_minimal,
  t_fluent,
  t_forest,
  t_github_dark,
  t_github_light,
  t_graphite,
  t_gruvbox_dark,
  t_gruvbox_light,
  t_high_contrast,
  t_kanagawa,
  t_lavender,
  t_light,
  t_material_you,
  t_midnight,
  t_mint,
  t_monokai,
  t_neo_brutalism,
  t_neumorphism,
  t_night_owl,
  t_nord,
  t_nord_light,
  t_ocean,
  t_oled_black,
  t_one_dark,
  t_paper,
  t_retro_95,
  t_rose,
  t_rose_pine,
  t_rose_pine_dawn,
  t_sand,
  t_sepia,
  t_snow,
  t_solarized_dark,
  t_solarized_light,
  t_sunset,
  t_terminal,
  t_tokyo_night,
  t_ubuntu_aubergine,
];
